on:
  push:
    tags:
      - "v*"

jobs:
  homebrew:
    name: Release Zed Extension
    runs-on: ubuntu-latest
    steps:
      # https://github.com/huacnlee/zed-extension-action
      - uses: huacnlee/zed-extension-action@v2
        with:
          extension-name: sqlmesh
          push-to: GitToby/zed-extensions
        env:
          # the personal access token should have "repo" & "workflow" scopes
          COMMITTER_TOKEN: ${{ secrets.ZED_SQLMESH_RELEASE_TOKEN }}
